// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module('TodoApp', []);

  app.controller('TodoCtrl', function($scope) {
    $scope.todos = [];
    $scope.createTodo = function(event) {
      if (event.keyCode !== 13) {
        return;
      }
      console.log("Add new todo: " + $scope.content);
      $scope.todos.push({
        "content": $scope.content,
        "done": false
      });
      return $scope.content = "";
    };
    $scope.stateChange = function(todo) {
      return console.log("State Change: " + todo.content + " - " + todo.done);
    };
    return $scope.removeTodo = function(todo) {
      console.log("Remove todo: " + todo.content + " - " + todo.done);
      return $scope.todos.splice($scope.todos.indexOf(todo), 1);
    };
  });

}).call(this);
